project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Camila Vargas Poulsen"
  # favicon: images/hex_logos/dndR_hex.png
  # repo-url: https://github.com/njlyon0/njlyon0.github.io
  # repo-actions: [issue]
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - text: my work
        menu: 
          - href: teaching.qmd
            text: teaching
          - href: portfolio.qmd
            text: portfolio
          - href: reflections.qmd
            text: reflections
          # - href: code-resources.qmd
          # - href: just-because.qmd
      - icon: github
        href: https://github.com/camilavargasp/camilavargasp.github.io
        target: _blank
  
  page-footer: 
    background: secondary
    left: © Copyright 2024, Camila Vargas Poulsen
    right: Built with {{< fa heart title="a heart" >}} using [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/camilavargasp/camilavargasp.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
        
format:
  html:
    # page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    mainfont: Cutive Mono
    toc: false
    link-external-newwindow: true
    link-external-icon: false


