project:
  type: website
  

website:
  title: "Camila Vargas Poulsen"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
        
  page-footer:
    center: "Copyright 2022, Camila Vargas Poulsen"
    background: secondary

format:
  html:
    theme: 
      light: cerulean
      dark: solar
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false

editor: visual

