project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Camila Vargas Poulsen"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: home
      - text: my work
        menu: 
          - href: teaching.qmd
            text: teaching
          - href: portfolio.qmd
            text: portfolio
      - icon: github
        href: https://github.com/camilavargasp/camilavargasp.github.io
        target: _blank
  
  page-footer: 
    background: secondary
    left: © Copyright 2024, Camila Vargas Poulsen
    right: Built with {{< fa heart title="a heart" >}} using [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/camilavargasp/camilavargasp.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
        
format:
  html:
    sidebar: false
    theme: 
      - styles.scss
    mainfont: "Cutive Mono"
    toc: false
    page-layout: full
    link-external-newwindow: true
    link-external-icon: false


